name: Orso Hypatos, the Gluttonous Bear
markdown: kramdown
permalink: /:year/:month/:day/:title
gems:
  - octopress-paginate
paginate_path:
  /page/:num/
google_analytics: UA-97187823-1
disqus:
    shortname: gluttonousbear